### ISSUE TITLE
Width must have an exact value or MATCH_PARENT

### ISSUE THREAD

**Issue by proud2008** [bingoogolapple/BGASwipeBackLayout-Android#105]
theme 设置 <item name="android:windowIsFloating">true</item>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="horizontal">
线性布局水平时 
会报错
W/System.err: java.lang.IllegalStateException: Width must have an exact value or MATCH_PARENT
        at cn.bingoogolapple.swipebacklayout.BGASwipeBackLayout.onMeasure(BGASwipeBackLayout.java:614)
        at android.view.View.measure(View.java:18020)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2775)
        at android.view.View.measure(View.java:18020)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2458)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1408)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1675)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1318)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6728)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
        at android.view.Choreographer.doCallbacks(Choreographer.java:605)
        at android.view.Choreographer.doFrame(Choreographer.java:574)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5898)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by manwuyuantao** [comment]
同问：

java.lang.IllegalStateException: Width must have an exact value or MATCH_PARENT
        at cn.bingoogolapple.swipebacklayout.BGASwipeBackLayout.onMeasure(BGASwipeBackLayout.java:597)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:737)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2782)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1608)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1919)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1523)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7395)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
        at android.view.Choreographer.doCallbacks(Choreographer.java:877)
        at android.view.Choreographer.doFrame(Choreographer.java:808)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by shiguiyou** [comment]
same error

**Comment by KORuL** [comment]
same error

**Comment by KORuL** [comment]
Need Clean and after Rebuild

**Comment by singlenoah** [comment]
各位这个问题解决了吗?
