### ISSUE TITLE
页面中的图片用Fresco加载，返回后图片会重新加载，现象是图片会闪一下

### ISSUE THREAD

**Issue by VanillaAlan** [bingoogolapple/BGASwipeBackLayout-Android#96]

**Comment by fangding** [comment]
添加忽略组件到ini接口。如下：
List<Class<? extends View>> list = new ArrayList<>();
list.add(ImageView.class);
list.add(SimpleDraweeView.class);
BGASwipeBackHelper.init(this, list);

**Comment by zhuoshirong** [comment]
是放在Application里面初始化吗

**Comment by zhuoshirong** [comment]
//  添加忽略组件到ini接口。如下：
        List<Class<? extends View>> list = new ArrayList<>();
        list.add(SimpleDraweeView.class);
        BGASwipeBackHelper.init(this, list);
添加了以后一返回就崩，测试三星S6，日志如下：

  Process: com.kmb2b.KmMall, PID: 8328
                                                                java.lang.OutOfMemoryError: Failed to allocate a 14745612 byte allocation with 14255816 free bytes and 13MB until OOM
                                                                    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                    at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
                                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:793)
                                                                    at cn.bingoogolapple.swipebacklayout.BGASwipeBackShadowView.getBitmap(BGASwipeBackShadowView.java:204)
                                                                    at cn.bingoogolapple.swipebacklayout.BGASwipeBackShadowView.unBindPreActivity(BGASwipeBackShadowView.java:150)
                                                                    at cn.bingoogolapple.swipebacklayout.BGASwipeBackLayout.dispatchOnPanelOpened(BGASwipeBackLayout.java:483)
                                                                    at cn.bingoogolapple.swipebacklayout.BGASwipeBackLayout$DragHelperCallback.onViewDragStateChanged(BGASwipeBackLayout.java:1512)
                                                                    at android.support.v4.widget.ViewDragHelper.setDragState(ViewDragHelper.java:881)
                                                                    at android.support.v4.widget.ViewDragHelper$2.run(ViewDragHelper.java:338)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by zhuoshirong** [comment]
不添加没事

**Comment by highBigger** [comment]
follow

**Comment by ztind** [comment]
> 添加忽略组件到ini接口。如下：
> List<Class<? extends View>> list = new ArrayList<>();
> list.add(ImageView.class);
> list.add(SimpleDraweeView.class);
> BGASwipeBackHelper.init(this, list);

没用勒

**Comment by princekin-f** [comment]
glide遇到同样问题
